name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_host: 'linux'
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_host: 'windows'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    # Linux-only setup step
    - name: Install Linux System Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build wget 
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 23
        sudo apt-get update
        sudo apt-get install -y clang-format-23

    # On Windows, we need to initialize the MSVC developer environment for Ninja to find 'cl'
    - name: Set up MSVC Developer Command Prompt
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'      
        host: ${{ matrix.qt_host }} # Dynamic host matching the current runner OS
        target: 'desktop'
        # modules: qtmultimedia
        arch: ${{ matrix.os == 'windows-latest' && 'win64_msvc2022_64' || '' }} # Sets the specific pre-compiled ABI for Windows
        install-deps: 'true'   

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build -G Ninja
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        ${{ matrix.os == 'ubuntu-latest' && '-DCLANG_FORMAT_COMMAND:PATH=/usr/bin/clang-format-23' || '' }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
